data_path: ../

nb_epochs: 50
learning_rate: 0.005
alpha: 0.1  # 0.01 recommended by the authors; nn.CrossEntropyLoss() if alpha = 1
batch_size: 512
k_folds: 5
device: cpu # cuda/cpu

pred_time: 63  # [27, 32, 37, 40, 44, 48, 53, 58, 63, 94]
closest_frame: 48 # -1 for every frames from 23.75

# You can choose either Image or Videos
image: true
backbone_name: mobilenet_v3_small # Look at pretrained_models.py for more models
intermediate_layers_size: 200
features_dim: 8

video: false
model_name: convLSTM # convLSTM / simple_model
cnn_layers: [32] # [8, 16, 32, 64]
